services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-dev}
    image: nttdevops-flask:${IMAGE_TAG:-dev}
    environment:
      - API_KEY_VALUE=2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
      - JWT_SECRET=secret-key-for-devops-api-ntt-data
    ports:
      - "8080:8080"
    deploy:
      replicas: 2

  kong:
    image: kong/kong-gateway:3.6
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - app
