resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress-kong.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: devops-api